### Application Infos
### ===========================================================
spring.application.name: '@project.name@'
server.port: '@server.port@'

### Application Config
### ===========================================================
# 必须引用
spring.profiles:
  include: def_full
  active: reg_eureka, alias_redis